<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Dapper.AOT" Version="1.0.52" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1" />
        <PackageReference Include="IdGen" Version="3.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.11" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
        <PackageReference Include="Polly" Version="8.7.0" />
        <PackageReference Include="Riok.Mapperly" Version="5.0.0-next.10" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\Auth\Controller\" />
      <Folder Include="Modules\Auth\Model\" />
      <Folder Include="Modules\Auth\Repositories\" />
      <Folder Include="Modules\Auth\Validators\" />
      <Folder Include="Modules\Base\Controller\" />
      <Folder Include="Modules\Base\Dto\Requests\" />
      <Folder Include="Modules\Base\Dto\Responses\" />
      <Folder Include="Modules\Base\Gateway\" />
      <Folder Include="Modules\Base\Mapper\" />
      <Folder Include="Modules\Base\Model\" />
      <Folder Include="Modules\Base\Repositories\" />
      <Folder Include="Modules\Base\Services\Base\" />
      <Folder Include="Modules\Base\Services\Provider\" />
      <Folder Include="Modules\Base\Validators\" />
      <Folder Include="Modules\RefreshToken\Controller\" />
      <Folder Include="Modules\RefreshToken\Dto\Requests\" />
      <Folder Include="Modules\RefreshToken\Mapper\" />
      <Folder Include="Modules\RefreshToken\Validators\" />
      <Folder Include="Modules\Role\Controller\" />
      <Folder Include="Modules\Role\Gateway\" />
      <Folder Include="Modules\Role\Validators\" />
      <Folder Include="Modules\UserRole\Controller\" />
      <Folder Include="Modules\UserRole\Validators\" />
      <Folder Include="Modules\User\Controller\" />
      <Folder Include="Modules\User\Validators\" />
    </ItemGroup>

</Project>
